apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dc3.service: dc3-data
  name: dc3-data
  namespace: dc3
spec:
  replicas: 1
  selector:
    matchLabels:
      dc3.version: develop
      dc3.network/dc3net: "true"
      dc3.service: dc3-data
  template:
    metadata:
      labels:
        dc3.version: develop
        dc3.network/dc3net: "true"
        dc3.service: dc3-data
    spec:
      containers:
        - image: pnoker/dc3-data:3.0
          name: dc3-data
          ports:
            - containerPort: 8500
      hostname: dc3-data
      restartPolicy: Always