apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dc3.service: dc3-nginx
  namespace: dc3
  name: dc3-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      dc3.version: develop
      dc3.network/dc3net: "true"
      dc3.service: dc3-nginx
  template:
    metadata:
      labels:
        dc3.version: develop
        dc3.network/dc3net: "true"
        dc3.service: dc3-nginx
    spec:
      containers:
        - image: pnoker/alpine-nginx:rtmp
          name: dc3-nginx
          ports:
            - containerPort: 1935
      hostname: dc3-nginx
      restartPolicy: Always