apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dc3.service: dc3-redis
  namespace: dc3
  name: dc3-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      dc3.version: develop
      dc3.network/dc3net: "true"
      dc3.service: dc3-redis
  template:
    metadata:
      labels:
        dc3.version: develop
        dc3.network/dc3net: "true"
        dc3.service: dc3-redis
    spec:
      containers:
        - image: pnoker/dc3-redis:3.0
          name: dc3-redis
          ports:
            - containerPort: 6379
      hostname: dc3-redis
      restartPolicy: Always