apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dc3.service: dc3-resource
  name: dc3-resource
  namespace: dc3
spec:
  replicas: 1
  selector:
    matchLabels:
      dc3.version: develop
      dc3.network/dc3net: "true"
      dc3.service: dc3-resource
  template:
    metadata:
      labels:
        dc3.version: develop
        dc3.network/dc3net: "true"
        dc3.service: dc3-resource
    spec:
      containers:
        - image: pnoker/dc3-resource:3.0
          name: dc3-resource
          ports:
            - containerPort: 8800
      hostname: dc3-resource
      restartPolicy: Always