apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dc3.service: dc3-opcua
  namespace: dc3
  name: dc3-opcua
spec:
  replicas: 1
  selector:
    matchLabels:
      dc3.version: develop
      dc3.network/dc3net: "true"
      dc3.service: dc3-opcua
  template:
    metadata:
      labels:
        dc3.version: develop
        dc3.network/dc3net: "true"
        dc3.service: dc3-opcua
    spec:
      containers:
        - image: pnoker/dc3-opcua:3.0
          name: dc3-opcua
          ports:
            - containerPort: 8802
      hostname: dc3-opcua
      restartPolicy: Always