server:
  port: 8400

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - register
      - monitor
      - server
      - rabbitmq
      - mysql
      - mongo
      - redis
      - feign
      #用于本地启动
      - dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  redis:
    database: 2
  cache:
    redis:
      time-to-live: ${CACHE_REDIS_TIME_TO_LIVE:12H}

logging:
  level:
    com.dc3: DEBUG
    #com.dc3.center.manager.service.rabbit: INFO
  file:
    name: dc3/logs/center/manager/${spring.application.name}.log
