server:
  port: 8100

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - server
      - register
      - monitor
      - ${environment:dev}

logging:
  level:
    com.dc3: DEBUG
  file:
    name: dc3/logs/center/register/${spring.application.name}.log

eureka:
  dashboard:
    path: ${EUREKA_DASHBOARD_PATH:/}
  client:
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9
