server:
  port: 8200

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - server
      - register
      - monitor
  boot:
    admin:
      context-path: ${MONITOR_CONTEXT_PATH:/}
      ui:
        title: DC3 Monitor Center
        public-url: ${MONITOR_PUBLIC_URL:/}
        favicon: /monitor/images/icon/favicon.ico
        favicon-danger: /monitor/images/icon/favicon-danger.ico
        brand: <img src="/monitor/images/logo/dc3-logo.png"><span>DC3 Monitor Center</span>

logging:
  level:
    com.dc3: DEBUG
  file:
    name: dc3/logs/center/monitor/${spring.application.name}.log