#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Product environment, customizable configuration
spring:
  redis:
    host: ${REDIS_HOST:dc3-redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:dc3}
  cache:
    redis:
      time-to-live: ${CACHE_REDIS_TIME_TO_LIVE:12H}
  cloud:
    nacos:
      server-addr: ${NACOS_HOST:dc3-register}:${NACOS_PORT:8848}
      username: dc3
      password: dc3
      discovery:
        namespace: ${NODE_ENV:pro}
    gateway:
      routes:
        # token
        - id: auth_route_token
          uri: lb://dc3-center-auth
          predicates:
            - Path=/api/v3/auth/token/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # auth
        - id: auth_route
          uri: lb://dc3-center-auth
          predicates:
            - Path=/api/v3/auth/user/**,/api/v3/auth/limited_ip/**,/api/v3/auth/tenant/**,/api/v3/auth/dictionary/**
          filters:
            - StripPrefix=2
            - Authentic
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # manager
        - id: manager_route
          uri: lb://dc3-center-manager
          predicates:
            - Path=/api/v3/manager/**
          filters:
            - StripPrefix=2
            - Authentic
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # data
        - id: data_route
          uri: lb://dc3-center-data
          predicates:
            - Path=/api/v3/data/**
          filters:
            - StripPrefix=2
            - Authentic
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: 'forward:/fallback'

grpc:
  client:
    dc3-center-auth:
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext