#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  influx:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-influx:2024.1.1.dev
    restart: always
    ports:
      - '38086:8086'
    container_name: dc3-influx
    hostname: dc3-influx
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-influx

volumes:
  influx_data:
  influx_config:

networks:
  dc3net:
    driver: bridge
...
