#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'

services:
  gateway:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-gateway:2024.1.1.dev
    restart: always
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=test
    container_name: dc3-gateway
    hostname: dc3-gateway
    volumes:
      - logs:/dc3-gateway/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-gateway

  auth:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-auth:2024.1.1.dev
    restart: always
    ports:
      - '8300:8300'
      - '9300:9300'
    environment:
      - NODE_ENV=test
    container_name: dc3-center-auth
    hostname: dc3-center-auth
    volumes:
      - logs:/dc3-center/dc3-center-auth/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-center-auth

  manager:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-manager:2024.1.1.dev
    restart: always
    ports:
      - '8400:8400'
      - '9400:9400'
    environment:
      - NODE_ENV=test
    container_name: dc3-center-manager
    hostname: dc3-center-manager
    volumes:
      - logs:/dc3-center/dc3-center-manager/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-center-manager

  data:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-data:2024.1.1.dev
    restart: always
    ports:
      - '8500:8500'
      - '9500:9500'
    environment:
      - NODE_ENV=test
    container_name: dc3-center-data
    hostname: dc3-center-data
    volumes:
      - logs:/dc3-center/dc3-center-data/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-center-data

  virtual:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-virtual:2024.1.1.dev
    restart: always
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-virtual
    hostname: dc3-driver-virtual
    volumes:
      - logs:/dc3-driver/dc3-driver-virtual/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-virtual

volumes:
  logs:

networks:
  dc3net:
    driver: bridge
...
