#
# Copyright 2016-present the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'

services:
  gateway:
    build:
      context: ../dc3-gateway/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-gateway:2023.4.0.dev
    restart: on-failure
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=test
    container_name: dc3-gateway
    hostname: dc3-gateway
    volumes:
      - logs:/dc3-gateway/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-gateway

  auth:
    build:
      context: ../dc3-center/dc3-center-auth/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-auth:2023.4.0.dev
    restart: on-failure
    ports:
      - '8300:8300'
    environment:
      - NODE_ENV=test
    container_name: dc3-center-auth
    hostname: dc3-center-auth
    volumes:
      - logs:/dc3-center/dc3-center-auth/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-center-auth

  manager:
    build:
      context: ../dc3-center/dc3-center-manager/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-manager:2023.4.0.dev
    restart: on-failure
    ports:
      - '8400:8400'
    environment:
      - NODE_ENV=test
    container_name: dc3-center-manager
    hostname: dc3-center-manager
    volumes:
      - logs:/dc3-center/dc3-center-manager/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-center-manager

  data:
    build:
      context: ../dc3-center/dc3-center-data/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-center-data:2023.4.0.dev
    restart: on-failure
    ports:
      - '8500:8500'
    environment:
      - NODE_ENV=test
    container_name: dc3-center-data
    hostname: dc3-center-data
    volumes:
      - logs:/dc3-center/dc3-center-data/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-center-data

  virtual:
    build:
      context: ../dc3-driver/dc3-driver-virtual/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-virtual:2023.4.0.dev
    restart: on-failure
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-virtual
    hostname: dc3-driver-virtual
    volumes:
      - logs:/dc3-driver/dc3-driver-virtual/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-virtual

  plcs7:
    build:
      context: ../dc3-driver/dc3-driver-plcs7/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-plcs7:2023.4.0.dev
    restart: on-failure
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-plcs7
    hostname: dc3-driver-plcs7
    volumes:
      - logs:/dc3-driver/dc3-driver-plcs7/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-plcs7

  opc-da:
    build:
      context: ../dc3-driver/dc3-driver-opc-da/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-opc-da:2023.4.0.dev
    restart: on-failure
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-opc-da
    hostname: dc3-driver-opc-da
    volumes:
      - logs:/dc3-driver/dc3-driver-opc-da/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-opc-da

  opc-ua:
    build:
      context: ../dc3-driver/dc3-driver-opc-ua/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-opc-ua:2023.4.0.dev
    restart: on-failure
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-opc-ua
    hostname: dc3-driver-opc-ua
    volumes:
      - logs:/dc3-driver/dc3-driver-opc-ua/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-opc-ua

  listening-virtual:
    build:
      context: ../dc3-driver/dc3-driver-listening-virtual/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-listening-virtual:2023.4.0.dev
    restart: on-failure
    ports:
      - '6270:6270'
      - '6271:6271'
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-listening-virtual
    hostname: dc3-driver-listening-virtual
    volumes:
      - logs:/dc3-driver/dc3-driver-listening-virtual/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-listening-virtual

  dtu-yeecom:
    build:
      context: ../dc3-driver/dc3-driver-dtu-yeecom/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-dtu-yeecom:2023.4.0.dev
    restart: on-failure
    ports:
      - '9001:9001'
      - '9002:9002'
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-dtu-yeecom
    hostname: dc3-driver-dtu-yeecom
    volumes:
      - logs:/dc3-driver/dc3-driver-dtu-yeecom/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-dtu-yeecom

  lwm2m:
    build:
      context: ../dc3-driver/dc3-driver-lwm2m/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-lwm2m:2023.4.0.dev
    restart: on-failure
    ports:
      - '5683:5683'
      - '5684:5684'
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-lwm2m
    hostname: dc3-driver-lwm2m
    volumes:
      - logs:/dc3-driver/dc3-driver-lwm2m/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-lwm2m

  mqtt:
    build:
      context: ../dc3-driver/dc3-driver-mqtt/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-mqtt:2023.4.0.dev
    restart: on-failure
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-mqtt
    hostname: dc3-driver-mqtt
    volumes:
      - logs:/dc3-driver/dc3-driver-mqtt/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-mqtt

  edge-gateway:
    build:
      context: ../dc3-driver/dc3-driver-edge-gateway/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-edge-gateway:2023.4.0.dev
    restart: on-failure
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-edge-gateway
    hostname: dc3-driver-edge-gateway
    volumes:
      - logs:/dc3-driver/dc3-driver-edge-gateway/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-edge-gateway

  modbus-tcp:
    build:
      context: ../dc3-driver/dc3-driver-modbus-tcp/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-modbus-tcp:2023.4.0.dev
    restart: on-failure
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-modbus-tcp
    hostname: dc3-driver-modbus-tcp
    volumes:
      - logs:/dc3-driver/dc3-driver-modbus-tcp/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-modbus-tcp

  weather-amap:
    build:
      context: ../dc3-driver/dc3-driver-weather-amap/
      dockerfile: ./Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-driver-weather-amap:2023.4.0.dev
    restart: on-failure
    environment:
      - NODE_ENV=test
    container_name: dc3-driver-weather-amap
    hostname: dc3-driver-weather-amap
    volumes:
      - logs:/dc3-driver/dc3-driver-weather-amap/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-driver-weather-amap

volumes:
  logs:

networks:
  dc3net:
    driver: bridge
...
