#
#  Copyright 2018-2020 Pnoker. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

version: '3'

services:
  dc3:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: pnoker/dc3:1.0.0

  gateway:
    build:
      context: ../dc3-gateway/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-gateway:1.0.0
    restart: always
    ports:
      - 8000:8000
    container_name: dc3-gateway
    hostname: dc3-gateway
    volumes:
      - logs:/dc3-gateway/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-gateway

  register:
    build:
      context: ../dc3-center/dc3-register/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-register:1.0.0
    restart: always
    ports:
      - 8100:8100
    container_name: dc3-register
    hostname: dc3-register
    volumes:
      - logs:/dc3-center/dc3-register/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-register

  monitor:
    build:
      context: ../dc3-center/dc3-monitor/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-monitor:1.0.0
    restart: always
    ports:
      - 8200:8200
    container_name: dc3-monitor
    hostname: dc3-monitor
    volumes:
      - logs:/dc3-center/dc3-monitor/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-monitor

  auth:
    build:
      context: ../dc3-center/dc3-auth/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-auth:1.0.0
    restart: always
    ports:
      - 8300:8300
    container_name: dc3-auth
    hostname: dc3-auth
    volumes:
      - logs:/dc3-center/dc3-auth/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-auth

  manager:
    build:
      context: ../dc3-center/dc3-manager/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-manager:1.0.0
    restart: always
    ports:
      - 8400:8400
    container_name: dc3-manager
    hostname: dc3-manager
    volumes:
      - logs:/dc3-center/dc3-manager/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-manager

  data:
    build:
      context: ../dc3-center/dc3-data/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-data:1.0.0
    restart: always
    ports:
      - 8500:8500
    container_name: dc3-data
    hostname: dc3-data
    volumes:
      - logs:/dc3-center/dc3-data/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-data

  virtual:
    build:
      context: ../dc3-driver/dc3-driver-virtual/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-driver-virtual:1.0.0
    restart: always
    ports:
      - 8600:8600
    container_name: dc3-driver-virtual
    hostname: dc3-driver-virtual
    volumes:
      - logs:/dc3-driver/dc3-driver-virtual/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-driver-virtual

  plcs7:
    build:
      context: ../dc3-driver/dc3-driver-plcs7/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-driver-plcs7:1.0.0
    restart: always
    ports:
      - 8601:8601
    container_name: dc3-driver-plcs7
    hostname: dc3-driver-plcs7
    volumes:
      - logs:/dc3-driver/dc3-driver-plcs7/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-driver-plcs7

  opc-da:
    build:
      context: ../dc3-driver/dc3-driver-opc-da/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-driver-opc-da:1.0.0
    restart: always
    ports:
      - 8602:8602
    container_name: dc3-driver-opc-da
    hostname: dc3-driver-opc-da
    volumes:
      - logs:/dc3-driver/dc3-driver-opc-da/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-driver-opc-da

  opc-ua:
    build:
      context: ../dc3-driver/dc3-driver-opc-ua/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-driver-opc-ua:1.0.0
    restart: always
    ports:
      - 8603:8603
    container_name: dc3-driver-opc-ua
    hostname: dc3-driver-opc-ua
    volumes:
      - logs:/dc3-driver/dc3-driver-opc-ua/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-driver-opc-ua

  listening-virtual:
    build:
      context: ../dc3-driver/dc3-driver-listening-virtual/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-driver-listening-virtual:1.0.0
    restart: always
    ports:
      - 8700:8700
    container_name: dc3-driver-listening-virtual
    hostname: dc3-driver-listening-virtual
    volumes:
      - logs:/dc3-driver/dc3-driver-listening-virtual/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-driver-listening-virtual

  mqtt:
    build:
      context: ../dc3-driver/dc3-driver-mqtt/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-driver-mqtt:1.0.0
    restart: always
    ports:
      - 8701:8701
    container_name: dc3-driver-mqtt
    hostname: dc3-driver-mqtt
    volumes:
      - logs:/dc3-driver/dc3-driver-mqtt/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-driver-mqtt

  modbus-tcp:
    build:
      context: ../dc3-driver/dc3-driver-modbus-tcp/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-driver-modbus-tcp:1.0.0
    restart: always
    ports:
      - 8604:8604
    container_name: dc3-driver-modbus-tcp
    hostname: dc3-driver-modbus-tcp
    volumes:
      - logs:/dc3-driver/dc3-driver-modbus-tcp/dc3/logs
    networks:
      dc3net:
        aliases:
          - dc3-driver-modbus-tcp

  rtmp:
    build:
      context: ../dc3-transfer/dc3-rtmp/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-rtmp:1.0.0
    restart: always
    ports:
      - 8803:8803
    container_name: dc3-rtmp
    hostname: dc3-rtmp
    networks:
      dc3net:
        aliases:
          - dc3-rtmp

  mysql:
    build:
      context: ./dependencies/mysql/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-mysql:1.0.0
    restart: always
    ports:
      - 3306:3306
    container_name: dc3-mysql
    hostname: dc3-mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      dc3net:
        aliases:
          - dc3-mysql

  mongo:
    build:
      context: ./dependencies/mongo/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-mongo:1.0.0
    restart: always
    ports:
      - 27017:27017
    container_name: dc3-mongo
    hostname: dc3-mongo
    volumes:
      - mongo_config:/data/configdb
      - mongo_db:/data/db
    networks:
      dc3net:
        aliases:
          - dc3-mongo

  redis:
    build:
      context: ./dependencies/redis/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-redis:1.0.0
    restart: always
    ports:
      - 6379:6379
    container_name: dc3-redis
    hostname: dc3-redis
    volumes:
      - redis:/data
    networks:
      dc3net:
        aliases:
          - dc3-redis

  rabbitmq:
    build:
      context: ./dependencies/rabbitmq/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-rabbitmq:1.0.0
    restart: always
    ports:
      - 5672:5672
      - 1883:1883
      - 61613:61613
      - 15672:15672
    container_name: dc3-rabbitmq
    hostname: dc3-rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      dc3net:
        aliases:
          - dc3-rabbitmq

  flink:
    image: flink:1.10
    restart: always
    expose:
      - 6121
      - 6122
    depends_on:
      - jobmanager
    container_name: dc3-flink-task
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      dc3net:
        aliases:
          - dc3-flink-task

  jobmanager:
    image: flink:1.10
    restart: always
    expose:
      - 6123
    ports:
      - 8081:8081
    container_name: dc3-flink-job
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      dc3net:
        aliases:
          - dc3-flink-job

  nginx-rtmp:
    image: pnoker/alpine-nginx:rtmp
    restart: always
    ports:
      - 1935:1935
    container_name: dc3-nginx
    hostname: dc3-nginx
    networks:
      dc3net:
        aliases:
          - dc3-nginx

  portainer:
    image:  portainer/portainer:alpine
    restart: always
    container_name: portainer
    hostname: dc3-portainer
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dc3net:
        aliases:
          - dc3-portainer

volumes:
  logs:
  mysql:
  mongo_config:
  mongo_db:
  redis:
  rabbitmq:
  portainer:

networks:
  dc3net:
    driver: 'bridge'
...
