rtmp:
  ffmpeg:
    window: D:/FFmpeg/bin/ffmpeg.exe
    unix: /usr/local/bin/ffmpeg
  task:
    reconnect-interval: 5000
    reconnect-max-times: 10
  thread:
    core-pool-size: 4
    maximum-pool-size: 32
    keep-alive-time: 10

server:
  port: 8803

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    database: 2
  cache:
    redis:
      time-to-live: 60S

logging:
  level:
    com.github.pnoker: DEBUG
  file:
    name: dc3/logs/transfer/${spring.application.name}.log