# Development environment, customizable configuration
eureka:
  instance:
    # Custom node registration IP
    ip-address: ${SERVICE_HOST:192.168.0.103}

spring:
  datasource:
    # Customize MySQL configuration
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/dc3?allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    # Customize Redis configuration
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    redis:
      # Customize Cache configuration
      time-to-live: ${CACHE_REDIS_TIME_TO_LIVE:5M}
