spring:
  data:
    mongodb:
      host: ${MONGO_HOST:dc3-mongo}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:dc3}
      auth-type: ${MONGO_AUTH_TYPE:password}
      username: ${MONGO_USERNAME:dc3}
      password: ${MONGO_PASSWORD:dc3}