#
# Copyright 2016-present the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

driver:
  tenant: default
  name: OpcDa驱动
  code: OpcDaDriver
  type: DRIVER
  remark: @project.description@
  schedule:
    # 定时读数据
    read:
      enable: true
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn: '0/5 * * * * ?'
  driver-attribute:
    - display-name: 主机
      attribute-name: host
      attribute-type-flag: STRING
      default-value: localhost
      remark: Opc Da Host
    - display-name: CLSID
      attribute-name: clsId
      attribute-type-flag: STRING
      default-value: F8582CF2-88FB-11D0-B850-00C0F0104305
      remark: Opc Da Server CLAID
    - display-name: 用户名
      attribute-name: username
      attribute-type-flag: STRING
      default-value: dc3
      remark: Opc Da UserName
    - display-name: 密码
      attribute-name: password
      attribute-type-flag: STRING
      default-value: dc3dc3
      remark: Opc Da Passward
  point-attribute:
    - display-name: 分组
      attribute-name: group
      attribute-type-flag: STRING
      default-value: GROUP
      remark: 分组名称
    - display-name: 位号
      attribute-name: tag
      attribute-type-flag: STRING
      default-value: TAG
      remark: 位号名称

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - ${NODE_ENV:dev}

logging:
  file:
    name: dc3/logs/driver/opcda/${spring.application.name}.log